name: Test

on:
  push:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make csvs dir
        run: mkdir ./csvs
      - name: Set some stuff
        id: set_stuff
        run: |
          echo "::set-output name=sheet-id::1isczfU4EgpWYVbp9FuzqxrNFImmknD4wMPSj4it8uoQ"
          echo "::set-output name=range-start::A1"
          echo "::set-output name=range-end::E2"
          echo "::set-output name=name::temp"
      - uses: cardinalby/google-api-fetch-token-action@v1
        id: fetch_token
        with:
          clientId: ${{ secrets.G_API_CLIENT_ID }}
          clientSecret: ${{ secrets.G_API_CLIENT_SECRET }}
          refreshToken: ${{ secrets.G_API_REFRESH_TOKEN }}
      - name: Pull GSheet data
        id: sheet_to_csv
        env:
          API_KEY: ${{ secrets.G_API_KEY }}
          TOKEN: ${{ steps.fetch_token.outputs.accessToken }}
          CSV_DIR: ./csvs
          SHEETS: '[{"id":"${{ steps.set_stuff.outputs.sheet-id }}","start":"${{ steps.set_stuff.outputs.range-start }}","end":"${{ steps.set_stuff.outputs.range-end }}","name":"${{ steps.set_stuff.outputs.name }}"},{"id":"${{ steps.set_stuff.outputs.sheet-id }}","start":"${{ steps.set_stuff.outputs.range-start }}"},{"id":"${{ steps.set_stuff.outputs.sheet-id }}","start":"${{ steps.set_stuff.outputs.range-start }}","end":"${{ steps.set_stuff.outputs.range-end }}","name":"${{ steps.set_stuff.outputs.name }}"}]'
        run: ./print-csv.sh "$SHEETS"
      - name: Print csv
        working-directory: ./csvs
        run: |
          echo "This is one csv:"
          cat 0.csv
          echo "This is another:"
          cat 2.csv

