name: Action Test

on:
  push:
env:
  id: '1ZbkUf1tAzt_Lhh1G8ezDgyU1AdUnm26xzPYLtdtWsI8'
  name: 'temp'
  range: 'A1:I8'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull GSheet data
        id: 'sheet_to_csv'
        uses: ./
        with:
          creds: ${{ secrets.GSHEET_CREDENTIALS }}
          output_json: True
          sheets: |
            [
              { "id": "${{ env.id }}", "range": "${{ env.range }}", "title": "${{ env.name }}" },
              { "id": "${{ env.id }}" }
            ]
      - name: Print csv
        id: "print_csv"
        run: |
          expected=(12 13500)
          for i in {0..1}; do
              echo "$FILES" | jq -c ".[${i}]" | while read j; do
                  eval file="${j}"
                  linecount="$(wc -l "${file}" | awk '{print $1}')"
                  if [ $linecount -ne "${expected[${i}]}" ]; then
                      echo "wc expected: ${expected[${i}]}; found ${linecount}; file ${file}"
                      exit 1
                  fi
                  echo "succeed: ${linecount} ${file}"
              done
          done
        env:
          FILES: ${{ steps.sheet_to_csv.outputs.results }}
      - name: Check permissions
        id: "check_perm"
        run: |
          expected=(777 777)
          for i in {0..1}; do
              echo "$FILES" | jq -c ".[${i}]" | while read j; do
                  eval file="${j}"
                  perm="$(stat -c '%a' "${file}")"
                  if [ $perm -ne "${expected[${i}]}" ]; then
                      echo "wc expected: ${expected[${i}]}; found ${linecount}; file ${file}"
                      exit 1
                  fi
                  echo "succeed: ${perm} ${file}"
              done
          done
        env:
          FILES: ${{ steps.sheet_to_csv.outputs.results }}
